# Generated by Django 4.0 on 2022-03-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='message',
            new_name='description',
        ),
    ]
