# Generated by Django 4.0 on 2022-03-08 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_desccription_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourworks',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='myapp.category'),
        ),
    ]
