# Generated by Django 4.0 on 2022-03-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_ourworks_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourworks',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='myapp.category'),
        ),
    ]
