# Generated by Django 4.0 on 2022-03-09 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_partner_alter_category_title_alter_news_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourworks',
            name='photo',
            field=models.ImageField(upload_to='images/', verbose_name='Asosiy rasim'),
        ),
        migrations.CreateModel(
            name='WorkImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/', verbose_name="Qo'shimcha rasm")),
                ('our_works', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ourworks')),
            ],
        ),
    ]
