# Generated by Django 4.0 on 2022-03-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_ourworks_photo_workimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourworks',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='Manzil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourworks',
            name='floor',
            field=models.IntegerField(default=1, verbose_name='Qavati'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourworks',
            name='size',
            field=models.IntegerField(default=1, verbose_name='Maydoni'),
            preserve_default=False,
        ),
    ]
