# Generated by Django 4.0 on 2022-03-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_ourworks_floor_alter_ourworks_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='rasmi')),
                ('title', models.CharField(max_length=128, verbose_name='nomi')),
            ],
        ),
    ]
